name: Ejecutar scraper simple

on:
  schedule:
    - cron: '0 19 * * *'  # Ejecuta todos los días a las 16:00 Argentina (19:00 UTC)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: |
          if [ -f package.json ]; then npm install; fi

      - run: node scraper.js
